name: Unit tests
on: [push, workflow_dispatch]
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          # shell script here
          python3 module.py
